#!/bin/bash

echo "pre-commit run"

#################################################
# eslint를 사용하여 문법 및 코드 스타일 체크.
################################################
chkStatus() {
    if [[ "$1" == 0 ]]; then
        echo "success"
        exit 0
    else
        echo "false"
        exit 1
    fi
}

nodeLint() {
    git diff --cached --name-only | while read FILE; do
        if [[ "$FILE" =~ ^sample-nodejs/.+(js)$ ]]; then
            echo "Running tests...$FILE"
            cd ${0%/*}/../../sample-nodejs && npm run lint
            status=$?
        fi
    done || chkStatus $status
}


echo "변경된 파일 :: " $(git diff --cached --name-only --diff-filter=ACM)

while : ; do
    read -p "커밋을 하시겠습니까? [y/n] " RESPONSE < /dev/tty
    case "${RESPONSE}" in
        [Yy]* ) nodeLint;  break;;
        [Nn]* ) exit 1;;
    esac
done


####################################################
# pre-commit project test 
####################################################
#echo "mvn test befero push"
#
#CWD=`pwd`
#MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#echo $MAIN_DIR
#cd $MAIN_DIR/../../
#MVN_RESULT=$(mvn clean test 2>&1)
#
#
#exit 1


###########################################################3
#PWD=`pwd`
#globalEmail=`git config --global --get user.email`
#signingKey=`git config --global --get user.signingkey`
#workEmail="example@axosoft.com"
#
#if [[ $PWD != "*demo*" && $globalEmail != $workEmail ]];
#then
#        echo "Commit email and global git config email differ"
#        echo "Global commit email: "$globalEmail""
#        echo "Committing email expected: $workEmail"
#        exit 1
#elif [[ $signingKey -eq "" ]];
#then
#        echo "No signing key found. Check global gitconfig"
#        exit 1
#else
#        echo ""
#        exit 0
#fi
